### ISSUE TITLE
Sth went wrong: Array ( )

### ISSUE THREAD

**Issue by irfannaseefp** [dereuromark/cakephp-captcha#11]
I am getting the following error. 

> Sth went wrong: Array ( )
BadMethodCallException
Documentation API
If you want to customize this error message, create src\Template\Error\error500.ctp
toggle vendor stack frames
⟩ Captcha\Model\Table\CaptchasTable->touch
ROOT\vendor\dereuromark\cakephp-captcha\src\View\Helper\CaptchaHelper.php, line 93
⟩ Captcha\View\Helper\CaptchaHelper->_getId
ROOT\vendor\dereuromark\cakephp-captcha\src\View\Helper\CaptchaHelper.php, line 51
![captcha](https://user-images.githubusercontent.com/3213896/56075454-a7283b80-5de0-11e9-899a-a5e58fe60f51.JPG)

Please help.

**Comment by dereuromark** [comment]
How do u use it?

**Comment by irfannaseefp** [comment]
In Cakephp 3.5.

**Comment by irfannaseefp** [comment]
Surprisingly it is working fine for some users , but some are getting this error in captcha loading in forms. I think I use an old version. How do I check the version ?

**Comment by dereuromark** [comment]
composer.lock

**Comment by irfannaseefp** [comment]
Composer.json file is as follows:

> {
	"name": "dereuromark/cakephp-captcha",
	"type": "cakephp-plugin",
	"description": "A CakePHP plugin to integrate captchas.",
	"keywords": ["cakephp", "plugin", "captchas", "security"],
	"homepage": "https://github.com/dereuromark/cakephp-captcha",
	"license": "MIT",
	"authors": [
		{
			"name": "Mark Scherer",
			"homepage": "http://www.dereuromark.de",
			"role": "Maintainer"
		}
	],
	"require": {
		"php": ">=5.6",
		"cakephp/cakephp": "^3.4",
		"paragonie/random_compat": "@stable"
	},
	"require-dev": {
		"cakephp/migrations": "@stable",
		"fig-r/psr2r-sniffer": "dev-master"
	},
	"autoload": {
		"psr-4": {
			"Captcha\\": "src",
			"Captcha\\Test\\Fixture\\": "tests/Fixture"
		}
	},
	"autoload-dev": {
		"psr-4": {
			"Captcha\\Test\\": "tests",
			"App\\": "tests/test_app/src",
			"Cake\\Test\\": "vendor/cakephp/cakephp/tests"
		}
	},
	"support": {
		"source": "https://github.com/dereuromark/cakephp-captcha"
	},
	"scripts": {
		"test": "php phpunit.phar",
		"test-setup": "[ ! -f phpunit.phar ] && wget https://phar.phpunit.de/phpunit-5.7.20.phar && mv phpunit-5.7.20.phar phpunit.phar || true",
		"test-coverage" : "php phpunit.phar --log-junit tmp/coverage/unitreport.xml --coverage-html tmp/coverage --coverage-clover tmp/coverage/coverage.xml",
		"phpstan": "phpstan analyse -c tests/phpstan.neon -l 3 src",
		"phpstan-setup": "cp composer.json composer.backup && composer require --dev phpstan/phpstan && mv composer.backup composer.json",
		"cs-check": "phpcs -v -p --standard=vendor/fig-r/psr2r-sniffer/PSR2R/ruleset.xml --ignore=/cakephp-captcha/vendor/,/tmp/,/logs/,/config/Migrations/ --extensions=php ./",
		"cs-fix": "phpcbf -v --standard=vendor/fig-r/psr2r-sniffer/PSR2R/ruleset.xml --ignore=/cakephp-captcha/vendor/,/tmp/,/logs/,/config/Migrations/ --extensions=php ./"
	}
}

**Comment by irfannaseefp** [comment]
To add to this, I found that for some users, Captcha is getting loaded properly without any error.

**Comment by dereuromark** [comment]
Why are you attaching the plugins composer file?

**Comment by irfannaseefp** [comment]
composer.json is contains line
> "dereuromark/cakephp-captcha": "^0.1.0"

**Comment by dereuromark** [comment]
Can you please compare what you did with the currently running/working https://sandbox.dereuromark.de/sandbox/captchas ?

**Comment by Brandon1811** [comment]
@irfannaseefp I'm sure you've resolved by now, but for anyone that encounters this in the future, check to be sure you aren't running into a throttling issue - [Throttle & Garbage Collect] (https://github.com/dereuromark/cakephp-captcha/tree/master/docs#throttle-and-garbage-collect)

I was having the same issue only in production, & it was caused by the captchas table not getting cleaned out.

Thanks @dereuromark for all the awesome :cake:
