### ISSUE TITLE
Captcha image is not displayed

### ISSUE THREAD

**Issue by calcosta** [dereuromark/cakephp-captcha#17]
CakePHP Version: 3.8.8
PHP Version: 7.3.12

The captcha image is not displayed.

This can be fixed by changing
line 5 in ```src/Template/Captcha/display.ctp``` 
```echo $captcha->image;```
to ```echo stream_get_contents($captcha->image);```

Any idea why this happens? Without the stream_get_contents function the output is only "Ressource id #xx" instead of the binary png data.

**Comment by dereuromark** [comment]
Can you make a PR here?
I am not sure why I dont face this issue locally or on the demo sandbox server.

**Comment by calcosta** [comment]
Yeah I'm just checking if it is a local issue since it works fine on our production server.
Strange thing is that it stopped working on production some days ago, now works again.

One problem in debug mode is a warning:
```Warning: Declaration of Captcha\Controller\CaptchaController::initialize() should be compatible with App\Controller\AppController::initialize($isError = false) [<b>ROOT/vendor/dereuromark/cakephp-captcha/src/Controller/CaptchaController.php</b>, line 12]```
which breaks the png output.

I'll just close the ticket, check if it's only a local issue and reopen it again if not.
Thanks for your help!
