### ISSUE TITLE
DB image column too small

### ISSUE THREAD

**Issue by idfake** [dereuromark/cakephp-captcha#2]
Sometimes the generated image for the math engine is larger than 255 bytes and then no captcha will be displayed.
I propose switching from BINARY to some other datatype since 255 is the max size for it, at least on MariaDB 10.2.

**Comment by dereuromark** [comment]
Are we talking about the same fields? https://github.com/dereuromark/cakephp-captcha/blob/master/config/Migrations/20160428093345_captcha_init.php#L41 does not contain any limit.
The limit is only on the result which is the string/number that you need to enter to solve the image.

**Comment by idfake** [comment]
Yes, but the limit is imposed by the database itself. It's also reflected in the phinx library that limits BINARY type by standard to 255.

**Comment by dereuromark** [comment]
how can we increase it?

**Comment by idfake** [comment]
I'm not exactly familiar with the whole cakephp stack yet and especially with the phinx lib, but after a quick glance i's say setting 'varbinary' and a limit of 512 should do.

**Comment by dereuromark** [comment]
OK, you can already do that on your project level side, and just ignore the plugin migration file :)
