### ISSUE TITLE
Captcha is only displayed if im logged in

### ISSUE THREAD

**Issue by Giesenhausener** [dereuromark/cakephp-captcha#20]
Hi,
thanks a lot for this plugin. 
I´m new to Cakephp and working on Cakephp 4 with the Authentication Plugin.
I want new users to register to my website and therefore i use your plugin.
But the captcha image is only shown if i´m already logged in to my website.
I added  in beforeFilter in CaptchaController.php the line `$this->Authenthication->addUnautenticatedActions(['display'])`
but it changed nothing.
Could you maybe give me a hint, what i should change?
Thanks in advance
Dirk

**Comment by dereuromark** [comment]
I am not familiar with this auth plugin, since I use TinyAuth to make controllers/actions more easily public.

Current code is still working with old AuthComponent:
https://github.com/dereuromark/cakephp-captcha/blob/master/src/Controller/CaptchaController.php#L34

Maybe we should also add a way to work with new one?

**Comment by Giesenhausener** [comment]
Thanks für your answer.
Maybe i had just a typo in my code.
Finally i got it working.

In beforeFilter in UsersController  i added `$this->Authentication->addUnauthenticatedActions(['register']);`
In beforeFilter in CaptchaController i added `$this->Authentication->addUnauthenticatedActions(['display']);`

Thanks again for this helpful plugin

**Comment by dereuromark** [comment]
Can you make a PR with your suggested changes?
Then we can just do both

if Auth component use current way, if Authentication component use your way.

**Comment by Giesenhausener** [comment]
I´m really new to this :-) 
What means "PR" ?

**Comment by dereuromark** [comment]
Pull Request
Can you check if https://github.com/dereuromark/cakephp-captcha/pull/22 solves it?
