### ISSUE TITLE
Exception thrown when maxPerUser is exceeded

### ISSUE THREAD

**Issue by zachee54** [dereuromark/cakephp-captcha#31]
I think this is a bug, although this behavior could be expected in some contexts.

## Expected behavior

When `maxPerUser` is exceeded, the captcha isn't saved in DB. The captcha shall then fail in every subsequent submit in the same session.

## Observed behavior

As soon as `maxPerUser` is exceeded, an exception is thrown with the message `Sth went wrong: Array`. The form can't be displayed any more.

## Cause

The MaxRule fails normally. Then, the saving operation fails normally too.
However, instead of displaying a simple flash error, `CaptchasTable::touch` throws a `BadMethodCallException` because `save()` method returned `false`.

This not only prevents bots to fill in the form any longer, but generates excessive error logs. If `maxPerUser` is set to a low value, human clients could also think that the site is down.
It would be better to display a smooth captcha error on submits.

**Comment by dereuromark** [comment]
Would you be able to make a PR with suggested changes?

**Comment by zachee54** [comment]
> Can you check if #32 solves it?

I get a notice when `CaptchaHelper` tries to display the image :
```Notice (8) : Uninitialized string offset: 0 [in /var/www/html/v2/vendor/cakephp/cakephp/src/Routing/Asset.php, line 159]```
This is because the given URL is empty in `CaptchaHelper::imageUrl()`.

Actually, I prefer saving and displaying the captcha normally in this situation, while making it unsolvable. I think it's also more readable in the code than testing everywhere whether the captcha exists.
Can you look at #33 ?
