### ISSUE TITLE
authorization checks not applied

### ISSUE THREAD

**Issue by idfake** [dereuromark/cakephp-captcha#42]
I have authorization turned on and when i try to use the plugin, the image won't display issueing 
```
The request to `/captcha/captcha/display/xxx` did not apply any authorization checks.
Authorization\Exception\AuthorizationRequiredException
```

The problem could be resolved by adding to CaptchController::beforeFilter:
```
if ($this->components()->has('Authorization') && method_exists($this->components()->get('Authorization'), 'skipAuthorization')) {
    $this->components()->get('Authorization')->skipAuthorization();
}
```
Can this be incorporated or is this a bad idea?

**Comment by dereuromark** [comment]
Isnt that already in there?
https://github.com/dereuromark/cakephp-captcha/blob/7e9b8a3b783bb18576bb44faa37189aec822b060/src/Controller/CaptchaController.php#L40-L44

**Comment by dereuromark** [comment]
Feel free to make a PR to add yours

**Comment by idfake** [comment]
gladly, thx.. #43
