### ISSUE TITLE
CakePHP 5.0.5 Unknown short option `b` + Undefined constant "Captcha\Model\Behavior\DAY"

### ISSUE THREAD

**Issue by hasentopf** [dereuromark/cakephp-captcha#44]
Hi Mark, after installing the Captcha Plugin I tried to follow your "active" instructions

1. Error: Unknown short option `b`.
`bin/cake plugin load Captcha -b -r`

2. Undefined constant "Captcha\Model\Behavior\DAY" in
CORE/src/ORM/BehaviorRegistry.php at line 152

**Comment by dereuromark** [comment]
Yeah, that text is old:
https://github.com/dereuromark/cakephp-captcha/commit/7abfdefafbd1110135e34995d67f703c275a1d13

As for the issue, I think that might be an app issue on your side.
The plugin is working fine in the sandbox: https://sandbox.dereuromark.de/sandbox/captchas
