### ISSUE TITLE
Image does not display

### ISSUE THREAD

**Issue by zipate** [dereuromark/cakephp-captcha#5]
Hi. The image only displays with this options `Plugin::load('Captcha', ['routes' => true, 'bootstrap' => true]);`. Without them, I get either an unknown routes error or no image.

**Comment by dereuromark** [comment]
Is there a PHP error? make sure you have met the server requirements for rendering images.

**Comment by dereuromark** [comment]
You can also compare with http://sandbox.dereuromark.de/sandbox/captchas/math

**Comment by zipate** [comment]
Loading the plugin as `Plugin::load('Captcha')` as stated in the documentation caused the errors. It only worked for me after adding the options. Thanks for the great plugin.

**Comment by dereuromark** [comment]
What did you have to do?
maybe we can fix the docs here?

**Comment by dereuromark** [comment]
['bootstrap' => true, 'routes' => true] right?

**Comment by dereuromark** [comment]
Fixed with https://github.com/dereuromark/cakephp-captcha/commit/deb584e2a2b164d1f6b267cf54dff35f2ef86067
Thanks a lot for your feedback!
